spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/VolcanoCamping?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: volcano
  driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework: DEBUG
